# Generated by Django 4.2 on 2025-08-18 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'doctor',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(help_text='Unique identifier for the employee (e.g., EMP001).', max_length=50, unique=True)),
                ('employee_name', models.CharField(help_text='Full name of the employee.', max_length=100)),
                ('department', models.CharField(help_text='Department where the employee works.', max_length=100)),
                ('designation', models.CharField(help_text='Job title or role of the employee.', max_length=100)),
                ('current_total_days', models.IntegerField(default=30, help_text='Current total available sick leave days.')),
                ('additional_sick_leave_days', models.IntegerField(default=0, help_text='Additional sick leave days granted.')),
                ('reason', models.CharField(blank=True, help_text='Reason for additional days', max_length=100, null=True)),
            ],
            options={
                'ordering': ['employee_name'],
            },
        ),
        migrations.CreateModel(
            name='SickLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sick_leave_days', models.IntegerField(default=30)),
                ('days_required', models.IntegerField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('patient_service', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('doctor_remarks', models.TextField()),
                ('recommendation', models.TextField()),
                ('document', models.FileField(blank=True, null=True, upload_to='sick_leave_documents/')),
                ('balance_days', models.IntegerField(blank=True, help_text='Remaining balance after deducting required days', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Doctor who approved the sick leave', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sick_app.doctor')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sick_leaves', to='sick_app.employee')),
            ],
            options={
                'verbose_name': 'Sick Leave',
                'verbose_name_plural': 'Sick Leaves',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sickleave',
            index=models.Index(fields=['employee'], name='sick_app_si_employe_61551f_idx'),
        ),
        migrations.AddIndex(
            model_name='sickleave',
            index=models.Index(fields=['created_by'], name='sick_app_si_created_250305_idx'),
        ),
        migrations.AddIndex(
            model_name='sickleave',
            index=models.Index(fields=['created_at'], name='sick_app_si_created_ed721f_idx'),
        ),
    ]
